# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'key_point.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1344, 866)
        MainWindow.setMinimumSize(QtCore.QSize(1344, 866))
        MainWindow.setMaximumSize(QtCore.QSize(1344, 866))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.prevButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevButton.setGeometry(QtCore.QRect(440, 670, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prevButton.setFont(font)
        self.prevButton.setObjectName("prevButton")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setGeometry(QtCore.QRect(680, 670, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.nameLabel = QtWidgets.QLabel(self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(20, 20, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.countLabel = QtWidgets.QLabel(self.centralwidget)
        self.countLabel.setGeometry(QtCore.QRect(650, 750, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.countLabel.setFont(font)
        self.countLabel.setObjectName("countLabel")
        self.annoView = QtWidgets.QLabel(self.centralwidget)
        self.annoView.setEnabled(True)
        self.annoView.setGeometry(QtCore.QRect(20, 50, 641, 581))
        self.annoView.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.annoView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.annoView.setLineWidth(1)
        self.annoView.setText("")
        self.annoView.setObjectName("annoView")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 630, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(960, 630, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.predView = QtWidgets.QLabel(self.centralwidget)
        self.predView.setEnabled(True)
        self.predView.setGeometry(QtCore.QRect(680, 50, 641, 581))
        self.predView.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 1px solid black;")
        self.predView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.predView.setLineWidth(1)
        self.predView.setText("")
        self.predView.setObjectName("predView")
        self.videoBufferSizeTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.videoBufferSizeTextEdit.setGeometry(QtCore.QRect(150, 670, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.videoBufferSizeTextEdit.setFont(font)
        self.videoBufferSizeTextEdit.setObjectName("videoBufferSizeTextEdit")
        self.nextVideoButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextVideoButton.setGeometry(QtCore.QRect(260, 770, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nextVideoButton.setFont(font)
        self.nextVideoButton.setObjectName("nextVideoButton")
        self.videoCountLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoCountLabel.setGeometry(QtCore.QRect(650, 790, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.videoCountLabel.setFont(font)
        self.videoCountLabel.setObjectName("videoCountLabel")
        self.videoBufferSizeLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoBufferSizeLabel.setGeometry(QtCore.QRect(20, 680, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.videoBufferSizeLabel.setFont(font)
        self.videoBufferSizeLabel.setObjectName("videoBufferSizeLabel")
        self.nextVideoFrameButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextVideoFrameButton.setGeometry(QtCore.QRect(1060, 670, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nextVideoFrameButton.setFont(font)
        self.nextVideoFrameButton.setObjectName("nextVideoFrameButton")
        self.prevVideoFrameButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevVideoFrameButton.setGeometry(QtCore.QRect(1060, 720, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prevVideoFrameButton.setFont(font)
        self.prevVideoFrameButton.setObjectName("prevVideoFrameButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 700, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.previousVideoButton = QtWidgets.QPushButton(self.centralwidget)
        self.previousVideoButton.setGeometry(QtCore.QRect(20, 770, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.previousVideoButton.setFont(font)
        self.previousVideoButton.setObjectName("previousVideoButton")
        self.videoFileCountLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoFileCountLabel.setGeometry(QtCore.QRect(230, 730, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.videoFileCountLabel.setFont(font)
        self.videoFileCountLabel.setObjectName("videoFileCountLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1344, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Image_Folder = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionOpen_Image_Folder.setFont(font)
        self.actionOpen_Image_Folder.setObjectName("actionOpen_Image_Folder")
        self.actionOpen_Video_Folder = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionOpen_Video_Folder.setFont(font)
        self.actionOpen_Video_Folder.setObjectName("actionOpen_Video_Folder")
        self.actionExit = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionExit.setFont(font)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionOpen_Image_Folder)
        self.menuMenu.addAction(self.actionOpen_Video_Folder)
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Key Point Prediction"))
        self.prevButton.setText(_translate("MainWindow", "Previous"))
        self.nextButton.setText(_translate("MainWindow", "Next"))
        self.nameLabel.setText(_translate("MainWindow", "None"))
        self.countLabel.setText(_translate("MainWindow", "N / N"))
        self.label_2.setText(_translate("MainWindow", "Annotation"))
        self.label_3.setText(_translate("MainWindow", "Prediction"))
        self.videoBufferSizeTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">10</p></body></html>"))
        self.nextVideoButton.setText(_translate("MainWindow", "Next Video"))
        self.videoCountLabel.setText(_translate("MainWindow", "N / N"))
        self.videoBufferSizeLabel.setText(_translate("MainWindow", "Video Buffer Size"))
        self.nextVideoFrameButton.setText(_translate("MainWindow", "Next Video Frame"))
        self.prevVideoFrameButton.setText(_translate("MainWindow", "Previous Video Frame"))
        self.label.setText(_translate("MainWindow", "Applies only when opening a video"))
        self.previousVideoButton.setText(_translate("MainWindow", "Previous Video"))
        self.videoFileCountLabel.setText(_translate("MainWindow", "N / N"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionOpen_Image_Folder.setText(_translate("MainWindow", "Open Image Folder"))
        self.actionOpen_Video_Folder.setText(_translate("MainWindow", "Open Video Folder"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

